//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortalEscolar.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensDeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensDeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortalEscolar.Exceptions.ResourceMensagensDeErro", typeof(ResourceMensagensDeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essse aluno não existe em nossa base de dados..
        /// </summary>
        public static string ALUNO_INEXISTENTE {
            get {
                return ResourceManager.GetString("ALUNO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data nascimento está inválido. o formato deve ser DD/MM/AAAA.
        /// </summary>
        public static string DATANASCIMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("DATANASCIMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Diretor deve ser maior que 18 anos..
        /// </summary>
        public static string DATANASCIMENTO_MENOS18ANOS {
            get {
                return ResourceManager.GetString("DATANASCIMENTO_MENOS18ANOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de nascimento deve ser informado..
        /// </summary>
        public static string DATANASCIMENTO_VAZIO {
            get {
                return ResourceManager.GetString("DATANASCIMENTO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse email já existe em nossa base de dados..
        /// </summary>
        public static string EMAIL_EXISTENTE {
            get {
                return ResourceManager.GetString("EMAIL_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email estar inválido..
        /// </summary>
        public static string EMAIL_INVALIDO {
            get {
                return ResourceManager.GetString("EMAIL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo email deve ser informado..
        /// </summary>
        public static string EMAIL_VAZIO {
            get {
                return ResourceManager.GetString("EMAIL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de entrega estar invalido. deve seguir esse formato: DD/MM/AAAA HH:MM.
        /// </summary>
        public static string ENVIAR_EXERCICIO_DATAENTREGA_INVALIDO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_DATAENTREGA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa disciplina não existe em nosso sistema..
        /// </summary>
        public static string ENVIAR_EXERCICIO_DISCIPLINA_INEXISTENTE {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_DISCIPLINA_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome só pode conter no maximo 200 caracteres..
        /// </summary>
        public static string ENVIAR_EXERCICIO_NOME_NOMAXIMO200CARACTERES {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_NOME_NOMAXIMO200CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome deve ser informado !!.
        /// </summary>
        public static string ENVIAR_EXERCICIO_NOME_VAZIO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_NOME_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo prazo de entrega aponta uma data passada..
        /// </summary>
        public static string ENVIAR_EXERCICIO_PRAZOENTREGA_PASSADO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_PRAZOENTREGA_PASSADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de entrega deve ser informado..
        /// </summary>
        public static string ENVIAR_EXERCICIO_PRAZOENTREGA_VAZIO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_PRAZOENTREGA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo alternativa correta deve ser informado..
        /// </summary>
        public static string ENVIAR_EXERCICIO_QUESTAO_ALTERNATIVACORRETA_VAZIO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_QUESTAO_ALTERNATIVACORRETA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve haver pelo menos duas alternativas..
        /// </summary>
        public static string ENVIAR_EXERCICIO_QUESTAO_ALTERNATIVAS_INVALIDO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_QUESTAO_ALTERNATIVAS_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe uma questão com o enunciado vazio..
        /// </summary>
        public static string ENVIAR_EXERCICIO_QUESTAO_ENUNCIADO_VAZIO {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_QUESTAO_ENUNCIADO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe ordens repetidas em alguma questão..
        /// </summary>
        public static string ENVIAR_EXERCICIO_QUESTAO_ORDEM_REPETIDAS {
            get {
                return ResourceManager.GetString("ENVIAR_EXERCICIO_QUESTAO_ORDEM_REPETIDAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro desconhecido..
        /// </summary>
        public static string ERRO_DESCONHECIDO {
            get {
                return ResourceManager.GetString("ERRO_DESCONHECIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessario um Diretor valido para executar essa ação..
        /// </summary>
        public static string ERRO_REGISTRAR_PROFESSOR_DIRETOR_INVALIDO {
            get {
                return ResourceManager.GetString("ERRO_REGISTRAR_PROFESSOR_DIRETOR_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O exercicio informado não existe..
        /// </summary>
        public static string EXERCICIO_INEXISTENTE {
            get {
                return ResourceManager.GetString("EXERCICIO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Invalido. Verifique suas credenciais..
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo cidade de nascimento do aluno deve conter no máximo 150 caracteres..
        /// </summary>
        public static string MATRICULA_CIDADENASCIMENTO_ALUNO_NOMAXIMO150CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_CIDADENASCIMENTO_ALUNO_NOMAXIMO150CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo cidade de nascimento do aluno está vazia..
        /// </summary>
        public static string MATRICULA_CIDADENASCIMENTO_ALUNO_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_CIDADENASCIMENTO_ALUNO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo cidade nascimento do responsavel deve conter no máximo 200 caracteres.
        /// </summary>
        public static string MATRICULA_CIDADENASCIMENTO_RESPONSAVEL_NOMAXIMO100CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_CIDADENASCIMENTO_RESPONSAVEL_NOMAXIMO100CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo cidade de nascimento do responsavel está vazia..
        /// </summary>
        public static string MATRICULA_CIDADENASCIMENTO_RESPONSAVEL_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_CIDADENASCIMENTO_RESPONSAVEL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF deve conter apenas números..
        /// </summary>
        public static string MATRICULA_CPF_RESPONSAVEL_APENAS_NUMEROS {
            get {
                return ResourceManager.GetString("MATRICULA_CPF_RESPONSAVEL_APENAS_NUMEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é invalido..
        /// </summary>
        public static string MATRICULA_CPF_RESPONSAVEL_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_CPF_RESPONSAVEL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF deve conter no minimo e no máximo 11 números..
        /// </summary>
        public static string MATRICULA_CPF_RESPONSAVEL_SOMENTE11NUMEROS {
            get {
                return ResourceManager.GetString("MATRICULA_CPF_RESPONSAVEL_SOMENTE11NUMEROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo CPF deve ser informado..
        /// </summary>
        public static string MATRICULA_CPF_RESPONSAVEL_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_CPF_RESPONSAVEL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data inicio está inválido. o formato deve ser DD/MM/AAAA.
        /// </summary>
        public static string MATRICULA_DATA_INICIO_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_INICIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de inicio deve ser informado..
        /// </summary>
        public static string MATRICULA_DATA_INICIO_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_INICIO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data nascimento do responsavel estar invalido..
        /// </summary>
        public static string MATRICULA_DATA_NASCIMENTO_RESPONSAVEL_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_NASCIMENTO_RESPONSAVEL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data nascimento do responsavel deve ser informado..
        /// </summary>
        public static string MATRICULA_DATA_NASCIMENTO_RESPONSAVEL_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_NASCIMENTO_RESPONSAVEL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data términio está inválido. o formato deve ser DD/MM/AAAA.
        /// </summary>
        public static string MATRICULA_DATA_TERMINIO_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_TERMINIO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo data de términio deve ser informado..
        /// </summary>
        public static string MATRICULA_DATA_TERMINIO_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_DATA_TERMINIO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data de inicio é maior ou igual a data de terminio..
        /// </summary>
        public static string MATRICULA_DATAINICIO_MAIOR_OU_IGUAL_DATATERMINIO {
            get {
                return ResourceManager.GetString("MATRICULA_DATAINICIO_MAIOR_OU_IGUAL_DATATERMINIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome completo do responsavel deve conter no máximo 20 caracteres.
        /// </summary>
        public static string MATRICULA_NOMECOMPLETO_RESPONSAVEL_NOMAXIMO200CARACTERES {
            get {
                return ResourceManager.GetString("MATRICULA_NOMECOMPLETO_RESPONSAVEL_NOMAXIMO200CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome completo do responsavel deve ser informado..
        /// </summary>
        public static string MATRICULA_NOMECOMPLETO_RESPONSAVEL_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_NOMECOMPLETO_RESPONSAVEL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O telefone do responsavel deve estar no formato XX X XXXX-XXXX.
        /// </summary>
        public static string MATRICULA_TELEFONE_RESPONSAVEL_INVALIDO {
            get {
                return ResourceManager.GetString("MATRICULA_TELEFONE_RESPONSAVEL_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo telefone do responsavel deve ser informado..
        /// </summary>
        public static string MATRICULA_TELEFONE_RESPONSAVEL_VAZIO {
            get {
                return ResourceManager.GetString("MATRICULA_TELEFONE_RESPONSAVEL_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome só pode conter no maximo 200 caracteres..
        /// </summary>
        public static string NOMECOMPLETO_MAXIMO200CARACTERES {
            get {
                return ResourceManager.GetString("NOMECOMPLETO_MAXIMO200CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome completo deve ser informado..
        /// </summary>
        public static string NOMECOMPLETO_VAZIO {
            get {
                return ResourceManager.GetString("NOMECOMPLETO_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professora não foi encontrada..
        /// </summary>
        public static string PROFESSORA_NAO_ENCONTRADA {
            get {
                return ResourceManager.GetString("PROFESSORA_NAO_ENCONTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno registrado com sucesso !.
        /// </summary>
        public static string REGISTRAR_ALUNO_SUCESSO {
            get {
                return ResourceManager.GetString("REGISTRAR_ALUNO_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professora registrado com sucesso !.
        /// </summary>
        public static string REGISTRAR_PROFESSORA_SUCESSO {
            get {
                return ResourceManager.GetString("REGISTRAR_PROFESSORA_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no minimo 6 caracteres..
        /// </summary>
        public static string SENHA_MINIMO_SEIS_CARACTERES {
            get {
                return ResourceManager.GetString("SENHA_MINIMO_SEIS_CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo senha deve ser informado..
        /// </summary>
        public static string SENHA_VAZIA {
            get {
                return ResourceManager.GetString("SENHA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Senha atual está inválida..
        /// </summary>
        public static string SENHAATUAL_INVALIDA {
            get {
                return ResourceManager.GetString("SENHAATUAL_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essa serie não existe em nossa escola..
        /// </summary>
        public static string SERIE_INEXISTENTE {
            get {
                return ResourceManager.GetString("SERIE_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Expirado !!.
        /// </summary>
        public static string TOKEN_EXPIRADO {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A turma informada não existe..
        /// </summary>
        public static string TURMA_INEXISTENTE {
            get {
                return ResourceManager.GetString("TURMA_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo sala deve conter no máximo 50 caracteres..
        /// </summary>
        public static string TURMA_NOME_TURMA_NOMAXIMO50CARACTERES {
            get {
                return ResourceManager.GetString("TURMA_NOME_TURMA_NOMAXIMO50CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo nome da turma deve ser informado..
        /// </summary>
        public static string TURMA_NOME_TURMA_VAZIO {
            get {
                return ResourceManager.GetString("TURMA_NOME_TURMA_VAZIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo sala deve conter no máximo 50 caracteres..
        /// </summary>
        public static string TURMA_SALA_NOMAXIMO50CARACTERES {
            get {
                return ResourceManager.GetString("TURMA_SALA_NOMAXIMO50CARACTERES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo sala deve ser informado..
        /// </summary>
        public static string TURMA_SALA_VAZIA {
            get {
                return ResourceManager.GetString("TURMA_SALA_VAZIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse turno não existe..
        /// </summary>
        public static string TURNO_INEXISTENTE {
            get {
                return ResourceManager.GetString("TURNO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuario não está autorizado realizar essa ação !!.
        /// </summary>
        public static string USUARIO_NAO_AUTORIZADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_AUTORIZADO", resourceCulture);
            }
        }
    }
}
